---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knowker-app-ingress
  namespace: knowker-dev
  labels:
    app: knowker-app
spec:
  ingressClassName: traefik
  rules:
    - host: knowker-dev.rd.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            frontend:
              service:
                name: knowker-frontend-service
                port:
                  number: 3001
