---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knowker-app-ingress
  namespace: knowker-prod
  labels:
    app: knowker-app
spec:
  ingressClassName: traefik
  rules:
    - host: knowker-prod.rd.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: knowker-app-service
                port:
                  number: 80
