apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowker-backend
  namespace: knowker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knowker-backend
  template:
    metadata:
      labels:
        app: knowker-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/knowker-rempo/knowker-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: backend.settings
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: "6379"
