---
apiVersion: v1
kind: Service
metadata:
  name: knowker-app-service
  namespace: knowker
  labels:
    app: knowker-app
spec:
  type: ClusterIP
  selector:
    app: knowker-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
