apiVersion: v1
kind: Service
metadata:
  name: knowker-frontend-service
  namespace: knowker
spec:
  type: ClusterIP
  selector:
    app: knowker-frontend
  ports:
    - name: http
      port: 3000       # The port that should be exposed
      targetPort: 3000 # Container port of the Node server
