apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knowker-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Knowker-rempo/rempo.git
    targetRevision: dev
    path: k8s/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: knowker-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
