apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knowker-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Knowker-rempo/rempo.git
    targetRevision: main
    path: k8s/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: knowker-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
