apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knowker-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Knowker-rempo/rempo.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: knowker

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
